### PR TITLE
Merge pull request #1 from nullxception/npe-fix

### PR DESCRIPTION
**Pull request by elluzion**
Check Null-safeness when switching optional-codecs state

### CODE REVIEW

**Comment by elluzion** [comment]
Just a fix from Derpfest I found when a person reported Bluetooth force closes in his car.
Building Arrow for Xiaomi cepheus (Mi9)

**Comment by justks** [comment]
should be on Gerrit, what's wrong with commit message? Is authorship ok? You should pick the actual commit and not merge commit.

**Comment by elluzion** [comment]
Oh okay, sorry

**Comment by justks** [comment]
https://blog.arrowos.net/posts/gerrit-guide

**Comment by elluzion** [comment]
Thanks, I never used Gerrit so i will do that now

**Pull request closed without merging**
